# Make sure this is set to "kotlinforforge"
modLoader="kotlinforforge"
# Make sure this is set to the appropriate version range
loaderVersion="[3,)" # Require at least 3.x
# License is REQUIRED after 1.16
license='MIT'

[[mods]]
modId="tgbridge"
version="${version}"
displayName="Telegram Bridge"
authors="vanutp"
description='''
'''
[[dependencies.tgbridge]]
    modId="forge"
    mandatory=true
    versionRange="[41,)"
    ordering="NONE"
    side="SERVER"
[[dependencies.tgbridge]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="SERVER"
