# Make sure this is set to "kotlinforforge"
modLoader="kotlinforforge"
# Make sure this is set to the appropriate version range
loaderVersion="[3,)"
# License is REQUIRED after 1.16
license='MIT'

[[mods]]
modId="tgbridge"
version="${version}"
displayName="Telegram Bridge"
authors="vanutp"
description='''
'''
[[dependencies.tgbridge]]
    modId="forge"
    mandatory=true
    versionRange="[43,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.tgbridge]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2]"
    ordering="NONE"
    side="BOTH"
