name: Build & Test

on:
  push: {}
  workflow_dispatch: {}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: gradle
          cache-dependency-path: |
            **/*.gradle*
            **/gradle.properties
            **/gradle-wrapper.properties
            gradle/*.versions.toml
            **/versions.properties

      - name: Run build
        run: ./gradlew build

      - uses: actions/upload-artifact@v4
        with:
          name: tgbridge
          path: build/release/*.jar
  test:
    name: Test
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: |
            8
            21
      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
      - uses: actions/download-artifact@v4
        with:
          name: tgbridge
          path: build/release/
      - uses: actions/cache@v4
        with:
          path: |
            tests/run/**
            !tests/run/*/world/**
            !tests/run/*/crash-reports/**
            !tests/run/*/logs/**
            !tests/run/**.log
          key: tests-${{ hashFiles('tests/src/**') }}

      - name: Run tests
        working-directory: tests
        run: deno run -A src/main.ts --no-build
